# Generated by Django 5.1.1 on 2024-09-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_alter_categoria_options_productoslavadora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Python'), (2, 'UI Interfaces'), (3, 'Javascript'), (4, 'Varios')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productoslavadora',
            options={'ordering': ['modelo'], 'verbose_name': 'lavadora', 'verbose_name_plural': 'lavadoras'},
        ),
    ]
