# Generated by Django 5.1.1 on 2024-09-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_programmingtopics_desarrollo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingtopics',
            name='desarrollo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
