# Generated by Django 5.1.1 on 2024-09-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0006_alter_programmingtopics_desarrollo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='name',
            field=models.CharField(choices=[('PYTHON', 'OPCION 1'), ('UI', 'OPCION 2'), ('JAVASCRIPT', 'OPCION 3'), ('VARIOS', 'OPCION 4')], default='PYTHON'),
        ),
    ]
