# Generated by Django 5.1.1 on 2024-09-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0007_alter_temas_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='name',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('UI', 'UI'), ('JAVASCRIPT', 'JAVASCRIPT'), ('VARIOS', 'VARIOS')], default='PYTHON'),
        ),
    ]
