# Generated by Django 5.1.1 on 2024-09-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0008_alter_temas_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingtopics',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmingtopics',
            name='desarrollo',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En Proceso'), (3, 'Completado')], default=1),
        ),
    ]
