# Generated by Django 5.1.1 on 2024-09-06 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0009_programmingtopics_contenido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingtopics',
            name='contenido',
        ),
    ]
