# Generated by Django 5.1.1 on 2024-09-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0012_blogtopics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTopics',
        ),
    ]
